In [1]:
import requests
import pandas as pd

In [2]:
API_URL = "https://clinicaltrials.gov/api/v2/studies"

params = {
    "query.cond": "Endometriosis",
    "pageSize": 5,
    "format": "json"
}

response = requests.get(API_URL, params=params, timeout=30)

print(response.status_code)

200

In [3]:
data = response.json()

data.keys()

dict_keys(['studies', 'nextPageToken'])

In [4]:
len(data["studies"])

5

In [5]:
data["studies"][0]

{'protocolSection': {'identificationModule': {'nctId': 'NCT06073379',
   'orgStudyIdInfo': {'id': 'POUHIN AOIparaM 2021'},
   'organization': {'fullName': 'Centre Hospitalier Universitaire Dijon',
    'class': 'OTHER'},
   'briefTitle': 'Efficacy of Korean Manupuncture on Pain in Women With Endometriosis: a Parallel-group Randomized Controlled Trial',
   'officialTitle': 'Efficacy of Korean Manupuncture on Pain in Women With Endometriosis: a Parallel-group Randomized Controlled Trial',
   'acronym': 'ENVOL'},
  'statusModule': {'statusVerifiedDate': '2026-02',
   'overallStatus': 'COMPLETED',
   'expandedAccessInfo': {'hasExpandedAccess': False},
   'startDateStruct': {'date': '2023-11-29', 'type': 'ACTUAL'},
   'primaryCompletionDateStruct': {'date': '2025-07-09', 'type': 'ACTUAL'},
   'completionDateStruct': {'date': '2025-07-09', 'type': 'ACTUAL'},
   'studyFirstSubmitDate': '2023-09-29',
   'studyFirstSubmitQcDate': '2023-10-05',
   'studyFirstPostDateStruct': {'date': '2023-10-10', 'type': 'ACTUAL'},
   'lastUpdateSubmitDate': '2026-02-06',
   'lastUpdatePostDateStruct': {'date': '2026-02-09', 'type': 'ACTUAL'}},
  'sponsorCollaboratorsModule': {'responsibleParty': {'type': 'SPONSOR'},
   'leadSponsor': {'name': 'Centre Hospitalier Universitaire Dijon',
    'class': 'OTHER'}},
  'oversightModule': {'isFdaRegulatedDrug': False,
   'isFdaRegulatedDevice': False},
  'descriptionModule': {'briefSummary': 'Endometriosis is defined as the presence and development of hormone-dependent endometrial tissue comprising both glands and stroma outside the endometrium and myometrium.\n\nIt affects 10-15% of women of childbearing age; of these, 25% are diagnosed following a consultation for infertility, and 25% following a consultation for pelvic pain.\n\nThis disease has a strong functional (pain and infertility) and organic impact, its numerous symptoms can have a considerable effect on quality of life.\n\nIndividualized analgesic management with multidisciplinary care (medical, surgical and psychological) can improve quality of life for women with endometriosis, but current treatment remains insufficient.\n\nKorean manupuncture is a complementary treatment technique that does not interact with current treatments. It\'s a holistic discipline that draws up a highly detailed map of the body\'s correspondence on the hand. Each body zone corresponds to a zone on the hand.\n\nThe aim of this research is to evaluate the effect of Korean manupuncture on endometriosis-related pain.\n\nPatients will be randomly assigned to 2 groups, 30 to the "Korean manupuncture" group and 30 to the "placebo/control" group. Patients will be blinded to their assigned group.'},
  'conditionsModule': {'conditions': ['Endometriosis', 'Pain']},
  'designModule': {'studyType': 'INTERVENTIONAL',
   'phases': ['NA'],
   'designInfo': {'allocation': 'RANDOMIZED',
    'interventionModel': 'PARALLEL',
    'primaryPurpose': 'SUPPORTIVE_CARE',
    'maskingInfo': {'masking': 'SINGLE', 'whoMasked': ['PARTICIPANT']}},
   'enrollmentInfo': {'count': 74, 'type': 'ACTUAL'}},
  'armsInterventionsModule': {'armGroups': [{'label': 'Korean manupuncture',
     'type': 'EXPERIMENTAL',
     'interventionNames': ['Other: Korean manupuncture']},
    {'label': 'Placebo/control',
     'type': 'PLACEBO_COMPARATOR',
     'interventionNames': ['Other: Placebo session']}],
   'interventions': [{'type': 'OTHER',
     'name': 'Korean manupuncture',
     'description': 'Energy assessment on hands and body Correspondence point technique on hands Energy rebalancing with ki Maeks on hands Moxa technique on hands',
     'armGroupLabels': ['Korean manupuncture']},
    {'type': 'OTHER',
     'name': 'Placebo session',
     'description': 'Energy assessment on hands and body Correspondence point technique on the hands Energy rebalancing with ki Maeks on hands (use of Qi bong) Moxa technique on hands (placebo moxas)',
     'armGroupLabels': ['Placebo/control']}]},
  'outcomesModule': {'primaryOutcomes': [{'measure': 'Variation in the Visual Analog Scale (VAS)',
     'timeFrame': 'Between Day 1 and Day 29'}]},
  'eligibilityModule': {'eligibilityCriteria': 'Inclusion Criteria:\n\n* Person having given oral consent\n* Woman of legal age\n* Woman diagnosed with endometriosis consulting for pain management\n\nExclusion Criteria:\n\n* Not affiliated to the national health insurance system\n* Person under legal protection (curatorship, guardianship)\n* Person under court order\n* Pregnant or breast-feeding women\n* Menopausal women (menopause is defined as amenorrhea lasting more than 12 consecutive months)\n* An adult unable to give consent\n* Women who have had a hysterectomy\n* Women who cannot speak or read French\n* Hands not accessible for treatment\n* Inability to follow the entire protocol\n* Cognitive impairment',
   'healthyVolunteers': False,
   'sex': 'ALL',
   'minimumAge': '18 Years',
   'stdAges': ['ADULT', 'OLDER_ADULT']},
  'contactsLocationsModule': {'locations': [{'facility': 'Chu Dijon Bourgogne',
     'city': 'Dijon',
     'country': 'France',
     'geoPoint': {'lat': 47.31344, 'lon': 5.01391}}]}},
 'derivedSection': {'miscInfoModule': {'versionHolder': '2026-07-29'},
  'conditionBrowseModule': {'meshes': [{'id': 'D004715',
     'term': 'Endometriosis'},
    {'id': 'D010146', 'term': 'Pain'}],
   'ancestors': [{'id': 'D005831', 'term': 'Genital Diseases, Female'},
    {'id': 'D052776', 'term': 'Female Urogenital Diseases'},
    {'id': 'D005261',
     'term': 'Female Urogenital Diseases and Pregnancy Complications'},
    {'id': 'D000091642', 'term': 'Urogenital Diseases'},
    {'id': 'D000091662', 'term': 'Genital Diseases'},
    {'id': 'D009461', 'term': 'Neurologic Manifestations'},
    {'id': 'D012816', 'term': 'Signs and Symptoms'},
    {'id': 'D013568',
     'term': 'Pathological Conditions, Signs and Symptoms'}]}},
 'hasResults': False}

In [6]:
first_study = data["studies"][0]

protocol = first_study["protocolSection"]
protocol.keys()

dict_keys(['identificationModule', 'statusModule', 'sponsorCollaboratorsModule', 'oversightModule', 'descriptionModule', 'conditionsModule', 'designModule', 'armsInterventionsModule', 'outcomesModule', 'eligibilityModule', 'contactsLocationsModule'])

In [7]:
identification = protocol["identificationModule"]

print("NCT ID:", identification["nctId"])
print("Title:", identification["briefTitle"])

NCT ID: NCT06073379
Title: Efficacy of Korean Manupuncture on Pain in Women With Endometriosis: a Parallel-group Randomized Controlled Trial

In [8]:
conditions = protocol.get("conditionsModule", {}).get("conditions", [])

print(conditions)

['Endometriosis', 'Pain']

In [9]:
def extract_basic_study_info(study: dict, searched_condition: str) -> dict:
    """Extract selected fields from one ClinicalTrials.gov study record."""

    protocol = study.get("protocolSection", {})

    identification = protocol.get("identificationModule", {})
    status = protocol.get("statusModule", {})
    design = protocol.get("designModule", {})
    conditions = protocol.get("conditionsModule", {})
    sponsor = protocol.get("sponsorCollaboratorsModule", {})
    eligibility = protocol.get("eligibilityModule", {})

    enrollment_info = design.get("enrollmentInfo", {})
    lead_sponsor = sponsor.get("leadSponsor", {})

    return {
        "nct_id": identification.get("nctId"),
        "searched_condition": searched_condition,
        "brief_title": identification.get("briefTitle"),
        "listed_conditions": conditions.get("conditions", []),
        "study_type": design.get("studyType"),
        "overall_status": status.get("overallStatus"),
        "enrollment": enrollment_info.get("count"),
        "enrollment_type": enrollment_info.get("type"),
        "lead_sponsor": lead_sponsor.get("name"),
        "sponsor_class": lead_sponsor.get("class"),
        "sex": eligibility.get("sex"),
        "has_results": study.get("hasResults", False),
    }

In [10]:
records = [
    extract_basic_study_info(
        study=study,
        searched_condition="Endometriosis"
    )
    for study in data["studies"]
]

sample_df = pd.DataFrame(records)

sample_df

,nct_id,searched_condition,brief_title,listed_conditions,study_type,overall_status,enrollment,enrollment_type,lead_sponsor,sponsor_class,sex,has_results
0,NCT06073379,Endometriosis,Efficacy of Korean Manupuncture on Pain in Wom...,"[Endometriosis, Pain]",INTERVENTIONAL,COMPLETED,74,ACTUAL,Centre Hospitalier Universitaire Dijon,OTHER,ALL,False
1,NCT06168097,Endometriosis,The Use of MicroRNAs Dysregulation as Potentia...,[Endometriosis],INTERVENTIONAL,ACTIVE_NOT_RECRUITING,200,ESTIMATED,"Asian Institute of Gastroenterology, India",OTHER,ALL,False
2,NCT00761683,Endometriosis,Non-Interventional Study to Evaluate Effect of...,[Endometriosis],OBSERVATIONAL,TERMINATED,105,ESTIMATED,AstraZeneca,INDUSTRY,FEMALE,False
3,NCT04614246,Endometriosis,Study to Gather Information How Well Three Dif...,[Endometriosis],INTERVENTIONAL,TERMINATED,215,ACTUAL,Bayer,INDUSTRY,FEMALE,True
4,NCT03928288,Endometriosis,Cabergoline for the Treatment of Chronic Pain ...,[Endometriosis],INTERVENTIONAL,COMPLETED,129,ACTUAL,Boston Children's Hospital,OTHER,FEMALE,False

In [11]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   nct_id              5 non-null      object
 1   searched_condition  5 non-null      object
 2   brief_title         5 non-null      object
 3   listed_conditions   5 non-null      object
 4   study_type          5 non-null      object
 5   overall_status      5 non-null      object
 6   enrollment          5 non-null      int64
 7   enrollment_type     5 non-null      object
 8   lead_sponsor        5 non-null      object
 9   sponsor_class       5 non-null      object
 10  sex                 5 non-null      object
 11  has_results         5 non-null      bool
dtypes: bool(1), int64(1), object(10)
memory usage: 573.0+ bytes

In [12]:
sample_df[
    [
        "nct_id",
        "searched_condition",
        "study_type",
        "overall_status",
        "enrollment",
        "has_results"
    ]
]

,nct_id,searched_condition,study_type,overall_status,enrollment,has_results
0,NCT06073379,Endometriosis,INTERVENTIONAL,COMPLETED,74,False
1,NCT06168097,Endometriosis,INTERVENTIONAL,ACTIVE_NOT_RECRUITING,200,False
2,NCT00761683,Endometriosis,OBSERVATIONAL,TERMINATED,105,False
3,NCT04614246,Endometriosis,INTERVENTIONAL,TERMINATED,215,True
4,NCT03928288,Endometriosis,INTERVENTIONAL,COMPLETED,129,False

In [13]:
sample_df.to_csv(
    "../data/raw/endometriosis_sample.csv",
    index=False
)